/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddToMyMiniProgram: typeof import('./../components/addToMyMiniProgram.vue')['default']
    Com1: typeof import('./../components/com1/index.vue')['default']
    MiniProgramTip: typeof import('./../components/miniProgramTip.vue')['default']
    TmApp: typeof import('@/tmui/components/tm-app/tm-app.vue')['default']
    TmButton: typeof import('@/tmui/components/tm-button/tm-button.vue')['default']
    TmIcon: typeof import('@/tmui/components/tm-icon/tm-icon.vue')['default']
    UvLine: typeof import('@climblee/uv-ui/components/uv-line/uv-line.vue')['default']
    UvLoadingIcon: typeof import('@climblee/uv-ui/components/uv-loading-icon/uv-loading-icon.vue')['default']
    UvLoadMore: typeof import('@climblee/uv-ui/components/uv-load-more/uv-load-more.vue')['default']
  }
}
